### ISSUE TITLE
Menu not displaying

### ISSUE THREAD

**Issue by FMCumhaill** [hsson/card-balance-app#12]
Today's menu not displaying. Just getting an error message saying it can't display. 

Running android 7.1.2 if that helps

**Comment by hsson** [comment]
Terribly sorry for the inconvenience. I've fixed the issue in the backend:
hsson/card-balance-backend@46532bfac9

Apparently the data source for the restaurant Linsen does not seem to be behaving correctly at the moment, which caused my backend to fail.
